### ISSUE TITLE
Add padding to left of :

### ISSUE THREAD

**Issue by martin-wiseweb** [adrianlee44/atom-aligner-scss#4]
It would be nice to have an option to choose which side of `:` you want to align your rules - much like in [aligner-javascript](https://github.com/adrianlee44/atom-aligner-javascript).

For example, when aligning CSS, I prefer this format:

```css
header {
    background-color : rgba(0,0,0,0.25);
    height           : 65px;
    line-height      : 65px;
    position         : absolute;
    text-align       : center;
    width            : 100%;
    z-index          : 2;
}
```
