### ISSUE TITLE
align locally by selector declaration block (vs. global file)?

### ISSUE THREAD

**Issue by jm3** [adrianlee44/atom-aligner-scss#5]
RFC: has there been any consideration of using only the local selector declaration block for alignment, rather than all selector blocks entire file globally? In a grouping like the following, it gives somewhat less legible results with unnecessarily wide margin gaps, which are eliminated when aligning on a declaration-block-local basis.

## Today:

```css
h2 {
  margin-bottom:  0.5rem;

  color:          hsla(255, 30%, 40%, 0.7);
  font-size:      1rem;
  letter-spacing: 0.1rem;
  text-transform: uppercase;
}

main {
  display:          grid;
}

* {
  border:           10px solid hsl(181, 38%, 46%); /* aka cadetblue aka #48a0a1 */
}
```

## Block-local:

```CSS
h2 {
  margin-bottom:  0.5rem;

  color:          hsla(255, 30%, 40%, 0.7);
  font-size:      1rem;
  letter-spacing: 0.1rem;
  text-transform: uppercase;
}

main {
  display: grid;
}

* {
  border:  10px solid hsl(181, 38%, 46%); /* aka cadetblue aka #48a0a1 */
}
```
